// Code generated by "stringer -type CBuildInType -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CUnknownType-0]
	_ = x[CVoid-1]
	_ = x[CBool-2]
	_ = x[CChar-3]
	_ = x[CShort-4]
	_ = x[CInt-5]
	_ = x[CLongLong-6]
	_ = x[CFloat-7]
	_ = x[CDouble-8]
	_ = x[CUnsignedChar-9]
	_ = x[CUnsignedShort-10]
	_ = x[CUnsignedInt-11]
	_ = x[CUnsignedLongLong-12]
}

const _CBuildInType_name = "CUnknownTypevoid_Boolcharshortintlong longfloatdoubleunsigned charunsigned shortunsigned intunsigned long long"

var _CBuildInType_index = [...]uint8{0, 12, 16, 21, 25, 30, 33, 42, 47, 53, 66, 80, 92, 110}

func (i CBuildInType) String() string {
	if i < 0 || i >= CBuildInType(len(_CBuildInType_index)-1) {
		return "CBuildInType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CBuildInType_name[_CBuildInType_index[i]:_CBuildInType_index[i+1]]
}
